export const API_GET_USER = "API_GET_USER";
export const API_GET_USER_SUCCESS = "API_GET_USER_SUCCESS";
export const API_GET_USER_FAILURE = "API_GET_USER_FAILURE";

export const API_USER_REGISTER = "API_USER_REGISTER";
export const API_USER_REGISTER_SUCCESS = "API_USER_REGISTER_SUCCESS";
export const API_USER_REGISTER_FAILURE = "API_USER_REGISTER_FAILURE";

export const API_USER_LOGIN = "API_USER_LOGIN";
export const API_USER_LOGIN_SUCCESS = "API_USER_LOGIN_SUCCESS";
export const API_USER_LOGIN_FAILURE = "API_USER_LOGIN_FAILURE";


export const API_GET_COMMISSIONS = "API_GET_COMMISSIONS";
export const API_GET_COMMISSIONS_SUCCESS = "API_GET_COMMISSIONS_SUCCESS";
export const API_GET_COMMISSIONS_FAILURE = "API_GET_COMMISSIONS_FAILURE";