export const API_GET_USER = "API_GET_USER";
export const API_GET_USER_SUCCESS = "API_GET_USER_SUCCESS";
export const API_GET_USER_FAILURE = "API_GET_USER_FAILURE";

export const API_USER_REGISTER = "API_USER_REGISTER";
export const API_USER_REGISTER_SUCCESS = "API_USER_REGISTER_SUCCESS";
export const API_USER_REGISTER_FAILURE = "API_USER_REGISTER_FAILURE";